# version is obsolete in newer compose; we omit it

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    environment:
      ALLOW_ORIGIN: "http://localhost:5500,http://127.0.0.1:5500"
      REDIS_URL: "redis://redis:6379/0"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      STORAGE_BUCKET: "media"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      REDIS_URL: "redis://redis:6379/0"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      STORAGE_BUCKET: "media"
    depends_on:
      - redis
      - minio

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

volumes:
  minio:
